version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - SECRET_KEY=b16467bd10cc44238e5bcbebb4663a75
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vasitadb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vasitadb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
