"""Comment body guncellemesi ve Upvote modeli eklendi

Revision ID: 1098471a7d9e
Revises: 6549e8863fc8
Create Date: 2026-05-30 13:56:57.328577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1098471a7d9e'
down_revision = '6549e8863fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'complaint_id', name='uix_user_complaint_upvote')
    )
    with op.batch_alter_table('upvote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upvote_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upvote_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('body')

    with op.batch_alter_table('upvote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upvote_user_id'))
        batch_op.drop_index(batch_op.f('ix_upvote_complaint_id'))

    op.drop_table('upvote')
    # ### end Alembic commands ###
