"""Modellere server_default eklendi

Revision ID: 6549e8863fc8
Revises: 
Create Date: 2026-05-29 19:12:54.510770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6549e8863fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=120), server_default='default.jpg', nullable=False))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=120), server_default='default_car.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_file')

    # ### end Alembic commands ###
